evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
_ajout:
    path:     /ajout
    defaults: { _controller: EvenementBundle:Evenement:Ajout }
_affiche:
    path:     /affiche
    defaults: { _controller: EvenementBundle:Evenement:Affiche }
_modifier:
    path:     /modifier/{id_Evenement}
    defaults: { _controller: EvenementBundle:Evenement:Modifier }
_supprimer:
    path:     /supprimer/{id_Evenement}
    defaults: { _controller: EvenementBundle:Evenement:Supprimer }
_affiche2:
    path:     /affiche2
    defaults: { _controller: EvenementBundle:Evenement:Affiche2 }
_ajoutComment:
    path:     /comment/{id_Evenement}
    defaults: { _controller: EvenementBundle:Commentaire:Comment }
_singleEvent:
    path:     /singleEvent/{id_Evenement}
    defaults: { _controller: EvenementBundle:Evenement:AfficheEvent }
_afficheCommentaire:
    path:     /afficheCommentaire/{id_Evenement}
    defaults: { _controller: EvenementBundle:Commentaire:AfficheCommentaire }
