<?php
/**
 * Created by PhpStorm.
 * User: Hosni
 * Date: 13/02/2018
 * Time: 23:17
 */

namespace MagasinBundle\Repository;

/**
 * MagasinRepository
 *
 * this class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProp($id)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.prop_magasin =:id')
            ->setParameter(':id',"$id");
        return $q->getQuery()->getResult();
    }
}