home:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }

Layout:
    path:     /layout
    defaults: { _controller: ProjetBundle:Default:Layout }

log:
    path:     /l
    defaults: { _controller: ProjetBundle:Login:login }
reg:
    path:     /r
    defaults: { _controller: ProjetBundle:Register:register }

back_office:
    path:     /b
    defaults: { _controller: ProjetBundle:Backoffice:back }
table:
    path:     /t
    defaults: { _controller: ProjetBundle:Table:table}
rech:
    path:     /recherche
    defaults: { _controller: UserBundle:User:Affiche}

_sup:
    path:     /sup/{id}
    defaults: { _controller: UserBundle:User:sup }
