home:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }

Layout:
    path:     /layout
    defaults: { _controller: ProjetBundle:Default:Layout }

log:
    path:     /l
    defaults: { _controller: ProjetBundle:Login:login }
reg:
    path:     /r
    defaults: { _controller: ProjetBundle:Register:register }

back_office:
    path:     /b
    defaults: { _controller: ProjetBundle:Backoffice:back2 }
back2_office:
    path:     /b2
    defaults: { _controller: ProjetBundle:Backoffice:back }
table:
    path:     /t
    defaults: { _controller: ProjetBundle:Table:table}
rech:
    path:     /recherche
    defaults: { _controller: UserBundle:User:Affiche}

_sup:
    path:     /sup/{id}
    defaults: { _controller: UserBundle:User:sup }
Produit_T:
    path:     /prod/
    defaults: { _controller: ProduitBundle:Produit:List2 }

admin-validate-produit:
    path:     /admin/produitvalidate/{id}
    defaults: { _controller: ProduitBundle:Produit:validate }
produit_supprim:
    path:     /supp/{id}
    defaults: { _controller: ProduitBundle:Produit:supr }

_graphePie:
    path: /pie
    defaults: { _controller: GrapheBundle:Default:index}
appannoce:
    path:     /appannoce
    defaults: { _controller: ProjetBundle:Backoffice:ApprouverAnnonce}
Accepter:
    path:     /Accepter/{id}
    defaults: { _controller: ProjetBundle:Backoffice:Accepter}
_supprimerannonce:
    path:     /supprimer/{idVenteLibre}
    defaults: { _controller:  ProjetBundle:Backoffice:SupprimerAnnonce }
